name: Feature Push

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SAM_TEMPLATE: template.yaml
      PIPELINE_EXECUTION_ROLE: arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/StreetlightPipelineRole
      CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/StreetlightCloudFormationRole
      ARTIFACTS_BUCKET: streetlight-pipeline-artifacts-${{ secrets.DEV_ACCOUNT_ID }}
      REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: aws-actions/setup-sam@v2
      - run: sam build --template ${SAM_TEMPLATE}

      - name: Assume the pipeline user role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: feature-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy CloudFormation Stack
        shell: bash
        run: |
          sam deploy --stack-name codecamp-2024-feature-dev \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${REGION} \
            --s3-bucket ${ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --role-arn ${CLOUDFORMATION_EXECUTION_ROLE} \
            --parameter-overrides Environment=dev PipelineRole=StreetlightPipelineRole "Title=\"Welcome to Code Camp 2024!\""
